name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    name: P8.2 - L9.* - prefer-lowest & prefer-stable - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, xdebug
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:10.*" "orchestra/testbench:9.*" --no-interaction --no-update
          composer update --prefer-lowest --prefer-stable --no-interaction --prefer-dist

      - name: Grant write permission to root
        run: chmod +w ./

      - name: Execute tests
        run: vendor/bin/pest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: build/logs/clover.xml
